name: CI
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: bahmutov/npm-install@v1
        with:
          working-directory: writting-tests/with-tap
          useLockFile: false
      # - uses: bahmutov/npm-install@v1
      #   with:
      #     working-directory: server
      #     useLockFile: false
